name: xcodebuild build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # Target the simulator using its unique ID to prevent name/OS collisions
          device_id=$(xcrun simctl list devices available | grep -m 1 "iPhone" | grep -oE '[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}')
          
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          if [ "$(ls -A | grep -i \.xcworkspace$)" ]; then 
            filetype_parameter="workspace"
            file_to_build="$(ls -A | grep -i \.xcworkspace$)"
          else 
            filetype_parameter="project"
            file_to_build="$(ls -A | grep -i \.xcodeproj$)"
          fi
          
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,id=$device_id"
